[env:esp32dev]
platform = platformio/espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 19200
board_build.partitions = huge_app.csv

[env:native]
platform = native
test_framework = unity
lib_compat_mode = off
test_build_src = yes
build_src_filter = +<Waveforms.cpp>
